version: '2'
services:
    bookcase-app:
        image: bookcase
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://bookcase-postgresql:5432/bookcase
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8088:8088
    bookcase-postgresql:
        extends:
            file: postgresql.yml
            service: bookcase-postgresql
